version: "3.10"

services:
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:${DB_NAME}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
  web:
    env_file:
      - .env
    build: .
    command: >
      sh -c "pip install --upgrade --upgrade-strategy only-if-needed pip
      && pip install -q -r requirements.txt
      && python manage.py collectstatic --no-input
      && gunicorn ImageUploadAPI.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media/
      - ./tests_media:/code/tests_media
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./static:/code/static
      - ./media:/code/media/
volumes:
  static: