# Generated by Django 3.2.9 on 2021-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedimage',
            name='testtext',
            field=models.CharField(blank=True, default='asdf', max_length=100, null=True),
        ),
    ]
