# Generated by Django 3.2.9 on 2021-11-12 11:56

import API.custom_validators
import API.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_storedimage_testtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedimage',
            name='testtext',
        ),
        migrations.AddField(
            model_name='storedimage',
            name='img_height',
            field=models.PositiveIntegerField(blank=True, default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedimage',
            name='img_width',
            field=models.PositiveIntegerField(blank=True, default=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='modified_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=API.models.user_directory_path, validators=[API.custom_validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='slug',
            field=models.SlugField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='storedimage',
            name='file',
            field=models.ImageField(height_field='img_height', upload_to=API.models.user_directory_path, validators=[API.custom_validators.validate_image_type], width_field='img_width'),
        ),
    ]
