# Generated by Django 3.2.9 on 2021-11-13 17:50

import API.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20211112_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='modified_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=API.models.user_directory_path),
        ),
    ]
