# Generated by Django 3.2.9 on 2021-11-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_storedimage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='modified_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
