# Generated by Django 3.2.9 on 2021-11-14 15:22

import API.custom_validators
import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_generatedimage_modified_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedimage',
            name='file',
            field=models.ImageField(height_field='img_height', upload_to=API.models.user_directory_path, validators=[API.custom_validators.validate_image_type], width_field='img_width'),
        ),
    ]
