# Generated by Django 3.2.9 on 2021-11-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_storedimage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='source_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thumbnails', to='API.storedimage'),
        ),
    ]
