# Generated by Django 3.2.9 on 2021-11-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_generatedimage_source_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='source_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generatedimage', to='API.storedimage'),
        ),
    ]
